baseurl = "http://www.nicksolomon.me"
theme = "hugo-uno"
languageCode = "en-us"
title = "Nick Solomon"
author = "Nick Solomon"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

ignoreFiles = [ "CONTRIBUTING\\.md$", "post/data/*" ]


[Params]
  AuthorName = "Nick"
  github = "nicksolomon"
  twitter = "NickSolomon10"
  email = "nick@nicksolomon.me"
  description = "A future data scientist in the Pacific Northwest."
  cover = "images/background-cover.jpg"
  logo = "images/bio-photo.jpg"
  [Params.Links]
    Shiny = {name = "Projects" , url = "/pages/projects"}
    About = {name = "About", url = "/pages/about"}

[params]
  highlightjsVersion = "9.9.0"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"
